### ISSUE TITLE
apiembed.com down

### ISSUE THREAD

**Issue by robvk** [Kong/apiembed#33]
It looks like the hosted website is down. Is this a temporary situation or should we be looking at alternatives?

**Comment by hutchic** [comment]
Sorry about that @robvk it should be back now 👍

**Comment by robvk** [comment]
I think api.apiembed.com has the same problem:

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/23367061/74635585-9bc34080-5166-11ea-817d-fded4dcc64e2.png">

**Comment by hutchic** [comment]
fixed now
